name: Create an issue
# on:
  # schedule:
  #   - cron:  '0 9 * * *' # 日本時間で毎日18時
on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create an Issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github\ISSUE_TEMPLATE\daily_report.md