# このワークフローはGitHubによって認定されていないアクションを使用します。
# それらはサードパーティによって提供され、
# 別個の利用規約、プライバシーポリシー、
# ドキュメントを参照してください。

# GitHub では、コミット SHA にアクションをピン留めすることが推奨されます。
# 新しいバージョンを取得するには、SHA を更新する必要があります。
# タグまたはブランチを参照することもできますが、アクションは警告なしに変更される可能性があります。

name: daily report issue create
# on:
  # schedule:
  #   - cron:  '0 9 * * *' # 日本時間で毎日18時
on: 
  workflow_dispatch:

jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Get the current date  # 作成日の取得
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Create team sync issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "inatchi"  # issueに割り当てるユーザー名
          # labels: ""  # Issueに適用するラベル
          title: "${{ steps.date.outputs.date }}_inatchi日報" # 作成日+Issueのタイトル
          # body: 参考ファイルはここで本文内容が直書きされていたが、templateを使用するのでコメントアウト
          pinned: false
          close-previous: false
          template: ".github/ISSUE_TEMPLATE/daily_report.md" # テンプレートの指定
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
